name: pathfinder-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas
      - scikit-learn
      - numpy
      - azure-ai-ml
      - azure-identity
      - joblib
