@extends('pathfinder.layout')

@section('title', 'MBTI Personality Assessment - Pathfinder')

@section('content')
<!-- Header Section -->
<div style="background: linear-gradient(to bottom right, #13264D, #5AA7C6);">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <div class="text-center">
            <h1 class="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-3 sm:mb-4">
                MBTI Personality Assessment
            </h1>
            <p class="text-base sm:text-lg md:text-xl max-w-3xl mx-auto mb-4 sm:mb-6 px-2" style="color: #EFF6FF; opacity: 0.9;">
                Discover your personality type through this comprehensive assessment based on the Myers-Briggs Type Indicator.
            </p>

            <!-- Assessment Description -->
            <div class="max-w-2xl mx-auto text-center">
                <div class="text-sm sm:text-base px-2" style="color: #EFF6FF; opacity: 0.8;">
                    Complete the comprehensive personality assessment to discover your MBTI type
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Assessment Content -->
<div class="py-12 sm:py-16 bg-gray-50">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">

        <!-- Progress Bar -->
        <div class="mb-6 sm:mb-8">
            <div class="flex items-center justify-between mb-2">
                <span class="text-sm font-medium text-gray-700">Progress</span>
                <span class="text-sm font-medium text-gray-700" id="progress-text">Page 1 of 10</span>
            </div>
            <div class="w-full bg-gray-200 rounded-full h-3">
                <div class="h-3 rounded-full transition-all duration-300" id="progress-bar" style="width: 10%; background-color: #5AA7C6;"></div>
            </div>
        </div>

        <!-- Steps Indicator -->
        <div class="flex justify-center mb-12">
            <div class="flex space-x-2">
                <div class="step-indicator active" data-step="1">1</div>
                <div class="step-indicator" data-step="2">2</div>
                <div class="step-indicator" data-step="3">3</div>
                <div class="step-indicator" data-step="4">4</div>
                <div class="step-indicator" data-step="5">5</div>
                <div class="step-indicator" data-step="6">6</div>
                <div class="step-indicator" data-step="7">7</div>
                <div class="step-indicator" data-step="8">8</div>
                <div class="step-indicator" data-step="9">9</div>
                <div class="step-indicator" data-step="10">10</div>
            </div>
        </div>

        <!-- Pro Tip Section -->
        <div class="bg-blue-50 rounded-lg p-6 mb-8">
            <h3 class="text-lg font-semibold text-blue-900 mb-3">💡 Pro Tip</h3>
            <p class="text-blue-800">
                Be honest about your preferences and tendencies. There are no right or wrong answers - this assessment works best when you respond authentically based on how you naturally think and behave.
            </p>
        </div>

        <!-- Questionnaire Form -->
        <form id="mbti-questionnaire-form" action="{{ route('pathfinder.mbti-questionnaire.process') }}" method="POST" class="space-y-8">
            @csrf
            <input type="hidden" id="current-page" name="current_page" value="1">
            <input type="hidden" id="all-responses" name="responses" value="">

            <!-- Questions will be dynamically generated by JavaScript -->
            <!-- This preserves the original design while allowing dynamic content -->

            <!-- Questions will be dynamically generated here -->
            <div id="questions-container" class="space-y-8 mb-12"></div>

            <!-- Navigation Buttons - Moved Below Questions -->
            <div class="flex flex-col sm:flex-row justify-between items-stretch sm:items-center mt-8 sm:mt-12 gap-3 sm:gap-0 pt-8 border-t border-gray-200">
                <button type="button" id="prev-btn" class="w-full sm:w-auto px-6 py-3 bg-gray-300 text-gray-700 font-medium rounded-lg hover:bg-gray-400 transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed min-h-[48px] order-2 sm:order-1" disabled>
                    Previous
                </button>
                <button type="button" id="next-btn" class="w-full sm:w-auto px-6 py-3 text-white font-medium rounded-lg transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed min-h-[48px] order-1 sm:order-2" style="background-color: #5AA7C6;" onmouseover="this.disabled || (this.style.backgroundColor='#13264D');" onmouseout="this.disabled || (this.style.backgroundColor='#5AA7C6');">
                    Next
                </button>
                <button type="submit" id="submit-btn" class="hidden w-full sm:w-auto px-6 py-3 text-white font-medium rounded-lg transition-colors duration-200 min-h-[48px]" style="background-color: #5AA7C6;" onmouseover="this.style.backgroundColor='#13264D';" onmouseout="this.style.backgroundColor='#5AA7C6');">
                    Complete Assessment
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

@push('styles')
<style>
    /* Question page styles */
    .question-page {
        display: none;
    }

    .question-page.active {
        display: block;
    }

    /* Step indicators */
    .step-indicator {
        width: 32px;
        height: 32px;
        border-radius: 50%;
        background-color: #e5e7eb;
        color: #6b7280;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: 600;
        font-size: 14px;
        transition: all 0.3s ease;
        cursor: pointer;
        user-select: none;
    }

    .step-indicator.active {
        background-color: #5AA7C6;
        color: white;
    }

    .step-indicator.completed {
        background-color: #10b981;
        color: white;
    }

    /* Modern radio button styling */
    .modern-radio-option {
        cursor: pointer;
        user-select: none;
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    }

    .modern-radio-option:hover {
        transform: translateY(-2px) scale(1.05);
    }

    input[type="radio"]:checked + .modern-radio-option .opacity-0 {
        opacity: 1 !important;
    }

    input[type="radio"]:checked + .modern-radio-option .opacity-0 .opacity-0 {
        opacity: 1 !important;
    }

    input[type="radio"]:checked + .modern-radio-option {
        transform: translateY(-2px) scale(1.1);
        box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
    }

    /* Show the gradient circle when selected */
    input[type="radio"]:checked + .modern-radio-option > div {
        opacity: 1 !important;
    }

    /* Show the white center dot when selected */
    input[type="radio"]:checked + .modern-radio-option > div > div {
        opacity: 1 !important;
    }

    /* Enhanced selected state for teal options */
    input[type="radio"]:checked + .modern-radio-option[data-value="7"],
    input[type="radio"]:checked + .modern-radio-option[data-value="6"],
    input[type="radio"]:checked + .modern-radio-option[data-value="5"] {
        background: linear-gradient(135deg, #14b8a6, #0d9488) !important;
        border-color: #0d9488 !important;
        color: white;
    }

    /* Enhanced selected state for blue options */
    input[type="radio"]:checked + .modern-radio-option[data-value="1"],
    input[type="radio"]:checked + .modern-radio-option[data-value="2"],
    input[type="radio"]:checked + .modern-radio-option[data-value="3"] {
        background: linear-gradient(135deg, #5AA7C6, #13264D) !important;
        border-color: #13264D !important;
        color: white;
    }

    /* Enhanced selected state for neutral option */
    input[type="radio"]:checked + .modern-radio-option[data-value="4"] {
        background: linear-gradient(135deg, #6b7280, #4b5563) !important;
        border-color: #4b5563 !important;
        color: white;
    }

    /* Pulse animation for selected state */
    @keyframes pulse-glow {
        0%, 100% { box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15); }
        50% { box-shadow: 0 8px 35px rgba(0, 0, 0, 0.25); }
    }

    input[type="radio"]:checked + .modern-radio-option {
        animation: pulse-glow 2s infinite;
    }
</style>
@endpush

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let currentPage = 1;
        const totalPages = 10;
        const questionsPerPage = 6;
        const responses = {};

        // MBTI Questions Database (60 questions total)
        const questions = {
            // Extraversion vs Introversion (E/I) - Questions 1-15
            1: "You regularly make new friends.",
            2: "You prefer to work in a team rather than alone.",
            3: "You enjoy being the center of attention.",
            4: "You feel comfortable in large social gatherings.",
            5: "You often initiate conversations with strangers.",
            6: "You feel energized after spending time with people.",
            7: "You prefer talking to thinking.",
            8: "You find it easy to introduce yourself to new people.",
            9: "You enjoy parties and social events.",
            10: "You feel comfortable being the leader in group activities.",
            11: "You prefer to express your thoughts out loud rather than in writing.",
            12: "You feel drained after spending too much time alone.",
            13: "You enjoy meeting new people at social events.",
            14: "You prefer group activities over solitary ones.",
            15: "You feel more comfortable speaking than listening.",

            // Sensing vs Intuition (S/N) - Questions 16-30
            16: "You prefer to focus on details rather than the big picture.",
            17: "You trust facts more than theories.",
            18: "You prefer practical solutions over innovative ideas.",
            19: "You focus on what is rather than what could be.",
            20: "You prefer step-by-step instructions.",
            21: "You trust your experience more than your intuition.",
            22: "You prefer concrete information over abstract concepts.",
            23: "You focus on present realities rather than future possibilities.",
            24: "You prefer proven methods over experimental approaches.",
            25: "You trust your five senses more than your hunches.",
            26: "You prefer specific examples over general principles.",
            27: "You focus on facts rather than meanings.",
            28: "You prefer routine over variety.",
            29: "You trust what you can see and touch.",
            30: "You prefer traditional approaches over innovative ones.",

            // Thinking vs Feeling (T/F) - Questions 31-45
            31: "You make decisions based on logic rather than emotions.",
            32: "You value truth more than harmony.",
            33: "You prefer to be objective rather than personal.",
            34: "You focus on tasks more than people.",
            35: "You believe being right is more important than being liked.",
            36: "You prefer criticism over praise.",
            37: "You make decisions with your head rather than your heart.",
            38: "You value competence more than compassion.",
            39: "You prefer to analyze rather than sympathize.",
            40: "You focus on principles rather than people.",
            41: "You believe justice is more important than mercy.",
            42: "You prefer logical arguments over emotional appeals.",
            43: "You value efficiency more than harmony.",
            44: "You prefer to be firm rather than gentle.",
            45: "You focus on what makes sense rather than what feels right.",

            // Judging vs Perceiving (J/P) - Questions 46-60
            46: "You prefer to have things settled rather than open-ended.",
            47: "You like to plan ahead rather than be spontaneous.",
            48: "You prefer structure over flexibility.",
            49: "You like to finish projects before starting new ones.",
            50: "You prefer deadlines to open timelines.",
            51: "You like to have a schedule rather than go with the flow.",
            52: "You prefer closure over keeping options open.",
            53: "You like to make decisions quickly.",
            54: "You prefer organized environments over messy ones.",
            55: "You like to have things planned out in advance.",
            56: "You prefer predictability over surprises.",
            57: "You like to stick to your plans rather than change them.",
            58: "You prefer to work steadily rather than in bursts.",
            59: "You like to have clear goals and objectives.",
            60: "You prefer to complete tasks rather than start new ones."
        };

        // Initialize first page
        showPage(1);
        updateProgress();
        updateNavigationButtons();

        // Navigation event listeners
        document.getElementById('prev-btn').addEventListener('click', function() {
            if (currentPage > 1) {
                saveCurrentPageResponses();
                currentPage--;
                showPage(currentPage);
                updateProgress();
                updateNavigationButtons(); // Update buttons when going back
                // Smooth scroll to top of the page
                window.scrollTo({
                    top: 0,
                    behavior: 'smooth'
                });
            }
        });

        document.getElementById('next-btn').addEventListener('click', function() {
            console.log('Next button clicked, current page:', currentPage);

            const validationResult = validateCurrentPage();
            console.log('Validation result:', validationResult);

            if (validationResult && currentPage < totalPages) {
                console.log('Proceeding to next page');
                saveCurrentPageResponses();
                currentPage++;
                console.log('New current page:', currentPage);
                showPage(currentPage);
                updateProgress();
                updateNavigationButtons(); // Check for early completion after each page
                // Smooth scroll to top of the page
                window.scrollTo({
                    top: 0,
                    behavior: 'smooth'
                });
            } else {
                console.log('Cannot proceed: validation failed or at last page');
            }
        });

        // Call updateNavigationButtons after each page change to check for early completion
        function nextPage() {
            if (validateCurrentPage()) {
                saveCurrentPageResponses();
                if (currentPage < totalPages) {
                    currentPage++;
                    showPage(currentPage);
                    updateProgress();
                    updateNavigationButtons(); // Check for early completion after each page
                }
            }
        }

        function prevPage() {
            if (currentPage > 1) {
                saveCurrentPageResponses();
                currentPage--;
                showPage(currentPage);
                updateProgress();
                updateNavigationButtons(); // Update buttons when going back
            }
        }

        // Form submission
        document.getElementById('mbti-questionnaire-form').addEventListener('submit', function(e) {
            e.preventDefault();

            // Validate current page first
            if (!validateCurrentPage()) {
                return;
            }

            saveCurrentPageResponses();

            // Verify all 60 questions are answered
            const answeredCount = Object.keys(responses).length;
            if (answeredCount < 60) {
                Swal.fire({
                    icon: 'warning',
                    title: 'Incomplete Assessment',
                    text: `Only ${answeredCount} of 60 questions answered. Please complete all pages.`,
                    confirmButtonColor: '#5AA7C6'
                });
                return;
            }

            // Prepare final responses
            document.getElementById('all-responses').value = JSON.stringify(responses);
            document.getElementById('current-page').value = currentPage;

            // Submit form
            this.submit();
        });

        function showPage(pageNum) {
            console.log('Showing page:', pageNum);

            // Hide all pages
            document.querySelectorAll('.question-page').forEach(page => {
                page.classList.remove('active');
            });

            // Show current page or create it if it doesn't exist
            let currentPageElement = document.getElementById(`page-${pageNum}`);
            if (!currentPageElement) {
                console.log('Creating page:', pageNum);
                currentPageElement = createPage(pageNum);
            }
            currentPageElement.classList.add('active');
            console.log('Page shown successfully');

            // Update step indicators
            document.querySelectorAll('.step-indicator').forEach((indicator, index) => {
                indicator.classList.remove('active', 'completed');
                if (index + 1 === pageNum) {
                    indicator.classList.add('active');
                } else if (index + 1 < pageNum) {
                    indicator.classList.add('completed');
                }
            });
        }

        function createPage(pageNum) {
            const startQuestion = (pageNum - 1) * questionsPerPage + 1;
            const endQuestion = Math.min(startQuestion + questionsPerPage - 1, 60);

            const pageDiv = document.createElement('div');
            pageDiv.className = 'question-page';
            pageDiv.id = `page-${pageNum}`;

            const questionsDiv = document.createElement('div');
            questionsDiv.className = 'space-y-8';

            for (let i = startQuestion; i <= endQuestion; i++) {
                const questionDiv = createQuestionElement(i, questions[i]);
                questionsDiv.appendChild(questionDiv);
            }

            pageDiv.appendChild(questionsDiv);

            // Insert into the questions container
            const questionsContainer = document.getElementById('questions-container');
            if (questionsContainer) {
                questionsContainer.appendChild(pageDiv);
            } else {
                // Fallback: Insert before navigation buttons
                const form = document.getElementById('mbti-questionnaire-form');
                const navButtons = form.querySelector('div.flex.justify-between');
                form.insertBefore(pageDiv, navButtons);
            }

            return pageDiv;
        }

        function createQuestionElement(questionNum, questionText) {
            const questionDiv = document.createElement('div');
            questionDiv.className = 'bg-white rounded-xl shadow-lg border border-gray-200 p-8 hover:shadow-xl transition-shadow duration-300';

            questionDiv.innerHTML = `
                <h2 class="text-2xl font-bold text-gray-900 mb-8 text-center">${questionText}</h2>
                <div class="flex items-center justify-between mb-4">
                    <span class="text-sm font-medium text-purple-600">Disagree</span>
                    <span class="text-sm font-medium text-teal-600">Agree</span>
                </div>
                <div class="flex items-center justify-center gap-8 mb-6">
                    ${createRadioOptions(questionNum)}
                </div>
            `;

            return questionDiv;
        }

        function createRadioOptions(questionNum) {
            let optionsHTML = '';
            const values = [1, 2, 3, 4, 5, 6, 7];
            const sizes = ['w-12 h-12', 'w-12 h-12', 'w-10 h-10', 'w-8 h-8', 'w-10 h-10', 'w-12 h-12', 'w-12 h-12'];
            const innerSizes = ['w-5 h-5', 'w-5 h-5', 'w-4 h-4', 'w-3 h-3', 'w-4 h-4', 'w-5 h-5', 'w-6 h-6'];
            const dotSizes = ['w-2 h-2', 'w-2 h-2', 'w-1.5 h-1.5', 'w-1 h-1', 'w-1.5 h-1.5', 'w-2 h-2', 'w-3 h-3'];

            values.forEach((value, index) => {
                const colorClass = value >= 5 ? 'teal' : value === 4 ? 'gray' : 'blue';
                const shadowClass = value === 7 || value === 1 ? 'hover:shadow-lg' : 'hover:shadow-md';

                const customStyle = value <= 3 ? `style="background: linear-gradient(to bottom right, #EFF6FF, #DBEAFE); border-color: #5AA7C6;"` :
                                   value === 4 ? `style="background: linear-gradient(to bottom right, #f9fafb, #f3f4f6); border-color: #9ca3af;"` :
                                   `style="background: linear-gradient(to bottom right, #f0fdfa, #ccfdf7); border-color: #14b8a6;"`;

                optionsHTML += `
                    <label for=\"q${questionNum}_${value}\" class=\"cursor-pointer block mx-2\">
                        <input type=\"radio\" id=\"q${questionNum}_${value}\" name=\"q${questionNum}\" value=\"${value}\" class=\"sr-only\" required>
                        <div class=\"modern-radio-option ${sizes[index]} rounded-xl border-2 ${shadowClass} transform hover:scale-105 transition-all duration-300 flex items-center justify-center group\" data-value=\"${value}\" ${customStyle}>
                            <div class=\"${innerSizes[index]} rounded-full opacity-0 group-hover:opacity-30 transition-all duration-300 flex items-center justify-center\" style=\"background: ${value <= 3 ? '#5AA7C6' : value === 4 ? '#9ca3af' : '#14b8a6'};\">
                                <div class=\"${dotSizes[index]} rounded-full bg-white opacity-0 transition-opacity duration-300\"></div>
                            </div>
                        </div>
                    </label>
                `;
            });

            return optionsHTML;
        }

        function validateCurrentPage() {
            console.log('Validating page:', currentPage);

            const currentPageElement = document.getElementById(`page-${currentPage}`);
            if (!currentPageElement) {
                console.log('Page element not found:', `page-${currentPage}`);
                return false;
            }

            // Get all unique question names on this page
            const questionNames = new Set();
            const allInputs = currentPageElement.querySelectorAll('input[type="radio"]');
            console.log('Found radio inputs:', allInputs.length);
            allInputs.forEach(input => questionNames.add(input.name));
            console.log('Question names on page:', Array.from(questionNames));

            // Check if each question has been answered
            for (let questionName of questionNames) {
                const answered = currentPageElement.querySelector(`input[name="${questionName}"]:checked`);
                console.log(`Question ${questionName} answered:`, !!answered);
                if (!answered) {
                    // Use SweetAlert for better user experience
                    Swal.fire({
                        icon: 'warning',
                        title: 'Question Required',
                        text: `Please answer question ${questionName.replace('q', '')} before proceeding.`,
                        confirmButtonColor: '#5AA7C6'
                    });
                    return false;
                }
            }
            console.log('All questions answered on page', currentPage);
            return true;
        }

        function saveCurrentPageResponses() {
            const currentPageElement = document.getElementById(`page-${currentPage}`);
            const inputs = currentPageElement.querySelectorAll('input[type="radio"]:checked');

            inputs.forEach(input => {
                responses[input.name] = parseInt(input.value);
            });
        }

        function updateProgress() {
            const progressPercent = (currentPage / totalPages) * 100;
            document.getElementById('progress-bar').style.width = `${progressPercent}%`;
            document.getElementById('progress-text').textContent = `Page ${currentPage} of ${totalPages}`;
        }

        function updateNavigationButtons() {
            const prevBtn = document.getElementById('prev-btn');
            const nextBtn = document.getElementById('next-btn');
            const submitBtn = document.getElementById('submit-btn');

            prevBtn.disabled = currentPage === 1;

            if (currentPage === totalPages) {
                nextBtn.style.display = 'none';
                submitBtn.style.display = 'block';
                submitBtn.textContent = 'Complete Assessment';
                submitBtn.style.backgroundColor = '#5AA7C6';
            } else {
                nextBtn.style.display = 'block';
                submitBtn.style.display = 'none';
            }
        }

        function checkEarlyCompletion() {
            // Disabled: require all 60 questions before completion
            return false;
        }
    });

    // Assessment Mode Toggle Functionality
    document.addEventListener('DOMContentLoaded', function() {

    });
</script>

<!-- Include MBTI RL System Scripts (kept for future improvements) -->
<script src="{{ asset('js/mbti-tester.js') }}"></script>
<script src="{{ asset('js/mbti-rl-agent.js') }}"></script>
<script src="{{ asset('js/mbti-rl-enhanced.js') }}"></script>

<script>
// RL System Integration (background only - not used for assessment flow)
let rlSystem = null;

// Initialize RL system in background for future improvements
document.addEventListener('DOMContentLoaded', function() {
    initializeRLSystem();
});

async function initializeRLSystem() {
    try {
        console.log('🚀 Initializing MBTI RL System (background)...');
        rlSystem = new MBTIRLEnhanced();
        await rlSystem.trainAgent(50); // Quick training
        console.log('✅ RL system ready (background mode)');
    } catch (error) {
        console.error('❌ RL system initialization failed:', error);
    }
}

// Standard Assessment Flow (simplified)
function startStandardAssessment() {
    // Show standard UI elements
    const stepIndicators = document.querySelector('.step-indicator');
    if (stepIndicators) {
        stepIndicators.parentElement.style.display = 'flex';
    }

    const progressBar = document.getElementById('progress-bar');
    if (progressBar) {
        progressBar.parentElement.style.display = 'block';
    }

    // Initialize standard assessment
    currentPage = 1;
    showPage(currentPage);
    updateProgress();
    updateNavigationButtons();

    console.log('🎯 Standard assessment started');
}

// Set the main assessment function
window.startAssessment = startStandardAssessment;

</script>
@endpush
