@extends('pathfinder.layout')

@section('title', 'MBTI Personality Assessment - Pathfinder')

@section('content')
<!-- Header Section -->
<div style="background: linear-gradient(to bottom right, #13264D, #5AA7C6);">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <div class="text-center">
            <h1 class="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-3 sm:mb-4">
                MBTI Personality Assessment
            </h1>
            <p class="text-base sm:text-lg md:text-xl max-w-3xl mx-auto mb-4 sm:mb-6 px-2" style="color: #EFF6FF; opacity: 0.9;">
                Discover your personality type through this comprehensive assessment based on the Myers-Briggs Type Indicator.
            </p>

            <!-- Assessment Description -->
            <div class="max-w-2xl mx-auto text-center">
                <div class="text-sm sm:text-base px-2" style="color: #EFF6FF; opacity: 0.8;">
                    Complete the comprehensive personality assessment to discover your MBTI type
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Assessment Content -->
<div class="py-12 sm:py-16 bg-gray-50">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">

        <!-- Progress Bar -->
        <div class="mb-6 sm:mb-8">
            <div class="flex items-center justify-between mb-2">
                <span class="text-sm font-medium text-gray-700">Progress</span>
                <span class="text-sm font-medium text-gray-700" id="progress-text">Page 1 of 10</span>
            </div>
            <div class="w-full bg-gray-200 rounded-full h-3">
                <div class="h-3 rounded-full transition-all duration-300" id="progress-bar" style="width: 10%; background-color: #5AA7C6;"></div>
            </div>
        </div>

        <!-- Steps Indicator -->
        <div class="flex justify-center mb-12">
            <div class="flex space-x-2">
                <div class="step-indicator active" data-step="1">1</div>
                <div class="step-indicator" data-step="2">2</div>
                <div class="step-indicator" data-step="3">3</div>
                <div class="step-indicator" data-step="4">4</div>
                <div class="step-indicator" data-step="5">5</div>
                <div class="step-indicator" data-step="6">6</div>
                <div class="step-indicator" data-step="7">7</div>
                <div class="step-indicator" data-step="8">8</div>
                <div class="step-indicator" data-step="9">9</div>
                <div class="step-indicator" data-step="10">10</div>
            </div>
        </div>

        <!-- Pro Tip Section -->
        <div class="bg-blue-50 rounded-lg p-6 mb-8">
            <h3 class="text-lg font-semibold text-blue-900 mb-3">💡 Pro Tip</h3>
            <p class="text-blue-800">
                Be honest about your preferences and tendencies. There are no right or wrong answers - this assessment works best when you respond authentically based on how you naturally think and behave.
            </p>
        </div>

        <!-- Questionnaire Form -->
        <form id="mbti-questionnaire-form" action="{{ route('pathfinder.mbti-questionnaire.process') }}" method="POST" class="space-y-8">
            @csrf
            <input type="hidden" id="current-page" name="current_page" value="1">
            <input type="hidden" id="all-responses" name="responses" value="">

            <!-- Questions will be dynamically generated by JavaScript -->
            <!-- This preserves the original design while allowing dynamic content -->

            <!-- Questions will be dynamically generated here -->
            <div id="questions-container" class="space-y-8 mb-12"></div>

            <!-- Navigation Buttons - Moved Below Questions -->
            <div class="flex flex-col sm:flex-row justify-between items-stretch sm:items-center mt-8 sm:mt-12 gap-3 sm:gap-0 pt-8 border-t border-gray-200">
                <button type="button" id="prev-btn" class="w-full sm:w-auto px-6 py-3 bg-gray-300 text-gray-700 font-medium rounded-lg hover:bg-gray-400 transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed min-h-[48px] order-2 sm:order-1" disabled>
                    Previous
                </button>
                <button type="button" id="next-btn" class="w-full sm:w-auto px-6 py-3 text-white font-medium rounded-lg transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed min-h-[48px] order-1 sm:order-2" style="background-color: #5AA7C6;" onmouseover="this.disabled || (this.style.backgroundColor='#13264D');" onmouseout="this.disabled || (this.style.backgroundColor='#5AA7C6');">
                    Next
                </button>
                <button type="submit" id="submit-btn" class="hidden w-full sm:w-auto px-6 py-3 text-white font-medium rounded-lg transition-colors duration-200 min-h-[48px]" style="background-color: #5AA7C6;" onmouseover="this.style.backgroundColor='#13264D';" onmouseout="this.style.backgroundColor='#5AA7C6');">
                    Complete Assessment
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

@push('styles')
<style>
    /* Question page styles */
    .question-page {
        display: none;
    }

    .question-page.active {
        display: block;
    }

    /* Step indicators */
    .step-indicator {
        width: 32px;
        height: 32px;
        border-radius: 50%;
        background-color: #e5e7eb;
        color: #6b7280;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: 600;
        font-size: 14px;
        transition: all 0.3s ease;
        cursor: pointer;
        user-select: none;
    }

    .step-indicator.active {
        background-color: #5AA7C6;
        color: white;
    }

    .step-indicator.completed {
        background-color: #10b981;
        color: white;
    }

    /* Modern radio button styling */
    .modern-radio-option {
        cursor: pointer;
        user-select: none;
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    }

    .modern-radio-option:hover {
        transform: translateY(-2px) scale(1.05);
    }

    input[type="radio"]:checked + .modern-radio-option .opacity-0 {
        opacity: 1 !important;
    }

    input[type="radio"]:checked + .modern-radio-option .opacity-0 .opacity-0 {
        opacity: 1 !important;
    }

    input[type="radio"]:checked + .modern-radio-option {
        transform: translateY(-2px) scale(1.1);
        box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
    }

    /* Show the gradient circle when selected */
    input[type="radio"]:checked + .modern-radio-option > div {
        opacity: 1 !important;
    }

    /* Show the white center dot when selected */
    input[type="radio"]:checked + .modern-radio-option > div > div {
        opacity: 1 !important;
    }

    /* Enhanced selected state for teal options */
    input[type="radio"]:checked + .modern-radio-option[data-value="7"],
    input[type="radio"]:checked + .modern-radio-option[data-value="6"],
    input[type="radio"]:checked + .modern-radio-option[data-value="5"] {
        background: linear-gradient(135deg, #14b8a6, #0d9488) !important;
        border-color: #0d9488 !important;
        color: white;
    }

    /* Enhanced selected state for blue options */
    input[type="radio"]:checked + .modern-radio-option[data-value="1"],
    input[type="radio"]:checked + .modern-radio-option[data-value="2"],
    input[type="radio"]:checked + .modern-radio-option[data-value="3"] {
        background: linear-gradient(135deg, #5AA7C6, #13264D) !important;
        border-color: #13264D !important;
        color: white;
    }

    /* Enhanced selected state for neutral option */
    input[type="radio"]:checked + .modern-radio-option[data-value="4"] {
        background: linear-gradient(135deg, #6b7280, #4b5563) !important;
        border-color: #4b5563 !important;
        color: white;
    }

    /* Pulse animation for selected state */
    @keyframes pulse-glow {
        0%, 100% { box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15); }
        50% { box-shadow: 0 8px 35px rgba(0, 0, 0, 0.25); }
    }

    input[type="radio"]:checked + .modern-radio-option {
        animation: pulse-glow 2s infinite;
    }
</style>
@endpush

@push('scripts')
@if(old('responses'))
<script>
    @php
        $oldResponses = old('responses');
        $oldResponsesJson = is_string($oldResponses) ? $oldResponses : json_encode($oldResponses ?: new \stdClass());
    @endphp
    window.oldResponses = {!! $oldResponsesJson !!};
    window.oldCurrentPage = {{ old('current_page', 1) }};
</script>
@endif
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let currentPage = window.oldCurrentPage || 1;
        const totalPages = 10;
        const questionsPerPage = 6;
        const responses = window.oldResponses || {};

        // MBTI Questions Database (60 questions — psychometrician-reviewed)
        const questions = {
            // Extraversion (E) vs. Introversion (I) — Questions 1–15
            // Source of energy: Social/External (E) vs. Solitary/Internal (I)
            1:  "You regularly make new friends.",                                          // E – valid (Q1)
            2:  "You prefer to work alone rather than in a team.",                          // I – valid (Q2)
            3:  "You enjoy being the center of attention.",                                  // E – valid (Q3)
            4:  "You prefer quiet environments to recharge after a busy day.",               // I – revised (Q4, was: stay relaxed)
            5:  "You often initiate conversations with strangers.",                         // E – valid (Q5)
            6:  "You tend to keep in the background during group activities.",              // I – valid (Q6)
            7:  "You are the first to start conversations in social settings.",             // E – valid (Q7)
            8:  "You prefer to think things through before you speak.",                     // I – revised (Q8, was: have little to say)
            9:  "You gain energy from being around other people.",                          // E – revised (Q9, was: feel comfortable)
            10: "You prefer to avoid large crowds or busy social gatherings.",              // I – valid (Q10)
            11: "You find it easy to meet and talk to new people.",                         // E – valid (Q11)
            12: "You find prolonged social interaction draining.",                          // I – revised (Q12, was: difficult to approach)
            13: "You prefer talking with others to sharing ideas in writing.",              // E – revised (Q13, was: skilled in handling)
            14: "You prefer one-on-one conversations over large group discussions.",        // I – revised (Q14, was: describe experiences as dull)
            15: "You take charge in conversations and group settings.",                     // E – valid (Q15)

            // Sensing (S) vs. Intuition (N) — Questions 16–30
            // Data processing: Concrete/Current (S) vs. Abstract/Future (N)
            16: "You prefer to focus on details rather than the big picture.",              // S – valid (Q16)
            17: "You tend to see the big picture rather than the specific details.",        // N – valid (Q17)
            18: "You prefer practical, hands-on solutions over theoretical ones.",         // S – valid (Q18)
            19: "You have a vivid imagination and enjoy exploring ideas.",                  // N – valid (Q19)
            20: "You prefer sticking to familiar, proven methods.",                         // S – valid (Q20)
            21: "You enjoy solving complex, abstract problems.",                            // N – valid (Q21)
            22: "You follow directions and established procedures carefully.",              // S – valid (Q22)
            23: "You are drawn to creating bold, original ideas.",                          // N – valid (Q23)
            24: "You prefer conventional, tried-and-tested approaches.",                    // S – valid (Q24)
            25: "You enjoy thinking deeply about ideas and concepts.",                      // N – valid (Q25)
            26: "You rarely look for hidden or deeper meanings behind things.",             // S – valid (Q26)
            27: "You prefer to focus on patterns and meanings behind facts.",               // N – revised (Q27, was: process large amounts of info)
            28: "You prefer to focus on one task at a time rather than multitasking.",     // S – valid (Q28)
            29: "You enjoy generating new ideas and brainstorming possibilities.",          // N – valid (Q29)
            30: "You prefer clear, concrete facts over abstract theories.",                 // S – revised (Q30, was: not interested in art — REJECTED)

            // Thinking (T) vs. Feeling (F) — Questions 31–45
            // Decision-making: Logic/Objective (T) vs. Values/Subjective (F)
            31: "You make decisions based on facts and logic rather than emotion.",         // T – valid (Q31)
            32: "You make a point to consider how others will feel about your decisions.", // F – valid (Q32)
            33: "You find it easier to make decisions based on logic than personal values.",// T – revised (Q33, was: political opinion — REJECTED)
            34: "You believe that laws and rules should be flexible based on circumstances.",// F – valid (Q34)
            35: "You prioritize logic over harmony when resolving a disagreement.",        // T – revised (Q35, was: optimism — REJECTED)
            36: "You are sensitive to the emotional needs of the people around you.",      // F – revised (Q36, was: I tend to worry — REJECTED)
            37: "You rely on logical reasoning when making important decisions.",           // T – valid (Q37)
            38: "You easily empathize with others and understand their feelings.",         // F – valid (Q38)
            39: "You remain objective and analytical even during personal conflicts.",      // T – revised (Q39, was: stay calm under pressure)
            40: "You often consider how a decision will emotionally affect those involved.",// F – revised (Q40, was: I get stressed easily — REJECTED)
            41: "You analyze the pros and cons carefully before committing to a decision.", // T – revised (Q41, was: rarely feel irritated — REJECTED)
            42: "You value kindness and compassion more than being technically correct.",   // F – revised (Q42, was: get upset easily — REJECTED)
            43: "You try to keep your personal feelings out of professional decisions.",   // T – revised (Q43, was: control emotions — ability framing)
            44: "You believe that a fair outcome matters more than how people feel about it.", // T – revised (Q44, was: mood swings — REJECTED)
            45: "You focus on the truth, even if it is uncomfortable for others to hear.", // T – revised (Q45, was: not easily bothered)

            // Judging (J) vs. Perceiving (P) — Questions 46–60
            // Work style: Planned/Structured (J) vs. Spontaneous/Flexible (P)
            46: "You prefer to have things settled and decided rather than left open.",    // J – valid (Q46)
            47: "You prefer to keep your options open rather than committing to a plan.",  // P – valid (Q47)
            48: "You like to stick to your plans once you have made them.",                // J – valid (Q48)
            49: "You are comfortable changing plans at the last minute.",                   // P – valid (Q49)
            50: "You enjoy organizing events and activities for others.",                   // J – valid (Q50)
            51: "You prefer spontaneity and flexibility over rigid schedules.",            // P – valid (Q51)
            52: "You prefer to finish tasks well ahead of the deadline.",                  // J – revised (Q52, was: complete tasks effectively)
            53: "You tend to forget to return things or put them back in their place.",    // P – valid (Q53)
            54: "You like to keep your workspace and belongings tidy and organized.",      // J – valid (Q54)
            55: "You tend to leave things scattered rather than organized.",               // P – valid (Q55)
            56: "You prefer following a schedule rather than making decisions on the fly.",// J – valid (Q56)
            57: "You are comfortable making decisions even when the situation is uncertain.", // P – revised (Q57, was: act without thinking — impulsivity)
            58: "You like to wrap up projects and tasks as soon as possible.",             // J – valid (Q58)
            59: "You prefer to delay decisions to keep all your options available.",       // P – valid (Q59)
            60: "You dislike leaving tasks unfinished or open-ended."                      // J – revised (Q60, was: I work hard — REJECTED)
        };

        // Initialize first page
        if (Object.keys(responses).length > 0) {
            // Restore previously answered pages
            const maxAnsweredPage = Math.ceil(Object.keys(responses).length / questionsPerPage);
            for (let i = 1; i <= Math.max(currentPage, maxAnsweredPage); i++) {
                showPage(i);
            }
        }
        showPage(currentPage);
        updateProgress();
        updateNavigationButtons();

        // Navigation event listeners
        document.getElementById('prev-btn').addEventListener('click', function() {
            if (currentPage > 1) {
                saveCurrentPageResponses();
                currentPage--;
                showPage(currentPage);
                updateProgress();
                updateNavigationButtons(); // Update buttons when going back
                // Smooth scroll to top of the page
                window.scrollTo({
                    top: 0,
                    behavior: 'smooth'
                });
            }
        });

        document.getElementById('next-btn').addEventListener('click', function() {
            console.log('Next button clicked, current page:', currentPage);

            const validationResult = validateCurrentPage();
            console.log('Validation result:', validationResult);

            if (validationResult && currentPage < totalPages) {
                console.log('Proceeding to next page');
                saveCurrentPageResponses();
                currentPage++;
                console.log('New current page:', currentPage);
                showPage(currentPage);
                updateProgress();
                updateNavigationButtons(); // Check for early completion after each page
                // Smooth scroll to top of the page
                window.scrollTo({
                    top: 0,
                    behavior: 'smooth'
                });
            } else {
                console.log('Cannot proceed: validation failed or at last page');
            }
        });

        // Call updateNavigationButtons after each page change to check for early completion
        function nextPage() {
            if (validateCurrentPage()) {
                saveCurrentPageResponses();
                if (currentPage < totalPages) {
                    currentPage++;
                    showPage(currentPage);
                    updateProgress();
                    updateNavigationButtons(); // Check for early completion after each page
                }
            }
        }

        function prevPage() {
            if (currentPage > 1) {
                saveCurrentPageResponses();
                currentPage--;
                showPage(currentPage);
                updateProgress();
                updateNavigationButtons(); // Update buttons when going back
            }
        }

        // Form submission
        document.getElementById('mbti-questionnaire-form').addEventListener('submit', function(e) {
            e.preventDefault();

            // Validate current page first
            if (!validateCurrentPage()) {
                return;
            }

            saveCurrentPageResponses();

            // Verify all 60 questions are answered
            const answeredCount = Object.keys(responses).length;
            if (answeredCount < 60) {
                Swal.fire({
                    icon: 'warning',
                    title: 'Incomplete Assessment',
                    text: `Only ${answeredCount} of 60 questions answered. Please complete all pages.`,
                    confirmButtonColor: '#5AA7C6'
                });
                return;
            }

            // Prepare final responses
            document.getElementById('all-responses').value = JSON.stringify(responses);
            document.getElementById('current-page').value = currentPage;

            // Submit form
            this.submit();
        });

        function showPage(pageNum) {
            console.log('Showing page:', pageNum);

            // Hide all pages
            document.querySelectorAll('.question-page').forEach(page => {
                page.classList.remove('active');
            });

            // Show current page or create it if it doesn't exist
            let currentPageElement = document.getElementById(`page-${pageNum}`);
            if (!currentPageElement) {
                console.log('Creating page:', pageNum);
                currentPageElement = createPage(pageNum);
            }
            currentPageElement.classList.add('active');
            console.log('Page shown successfully');

            // Update step indicators
            document.querySelectorAll('.step-indicator').forEach((indicator, index) => {
                indicator.classList.remove('active', 'completed');
                if (index + 1 === pageNum) {
                    indicator.classList.add('active');
                } else if (index + 1 < pageNum) {
                    indicator.classList.add('completed');
                }
            });
        }

        function createPage(pageNum) {
            const startQuestion = (pageNum - 1) * questionsPerPage + 1;
            const endQuestion = Math.min(startQuestion + questionsPerPage - 1, 60);

            const pageDiv = document.createElement('div');
            pageDiv.className = 'question-page';
            pageDiv.id = `page-${pageNum}`;

            const questionsDiv = document.createElement('div');
            questionsDiv.className = 'space-y-8';

            for (let i = startQuestion; i <= endQuestion; i++) {
                const questionDiv = createQuestionElement(i, questions[i]);
                questionsDiv.appendChild(questionDiv);
            }

            pageDiv.appendChild(questionsDiv);

            // Insert into the questions container
            const questionsContainer = document.getElementById('questions-container');
            if (questionsContainer) {
                questionsContainer.appendChild(pageDiv);
            } else {
                // Fallback: Insert before navigation buttons
                const form = document.getElementById('mbti-questionnaire-form');
                const navButtons = form.querySelector('div.flex.justify-between');
                form.insertBefore(pageDiv, navButtons);
            }

            return pageDiv;
        }

        function createQuestionElement(questionNum, questionText) {
            const questionDiv = document.createElement('div');
            questionDiv.className = 'bg-white rounded-xl shadow-lg border border-gray-200 p-8 hover:shadow-xl transition-shadow duration-300';

            questionDiv.innerHTML = `
                <h2 class="text-2xl font-bold text-gray-900 mb-8 text-center">${questionText}</h2>
                <div class="flex items-center justify-between mb-4">
                    <span class="text-sm font-medium text-purple-600">Disagree</span>
                    <span class="text-sm font-medium text-teal-600">Agree</span>
                </div>
                <div class="flex items-center justify-center gap-8 mb-6">
                    ${createRadioOptions(questionNum)}
                </div>
            `;

            return questionDiv;
        }

        function createRadioOptions(questionNum) {
            let optionsHTML = '';
            const values = [1, 2, 3, 4, 5, 6, 7];
            const sizes = ['w-12 h-12', 'w-12 h-12', 'w-10 h-10', 'w-8 h-8', 'w-10 h-10', 'w-12 h-12', 'w-12 h-12'];
            const innerSizes = ['w-5 h-5', 'w-5 h-5', 'w-4 h-4', 'w-3 h-3', 'w-4 h-4', 'w-5 h-5', 'w-6 h-6'];
            const dotSizes = ['w-2 h-2', 'w-2 h-2', 'w-1.5 h-1.5', 'w-1 h-1', 'w-1.5 h-1.5', 'w-2 h-2', 'w-3 h-3'];

            values.forEach((value, index) => {
                const colorClass = value >= 5 ? 'teal' : value === 4 ? 'gray' : 'blue';
                const shadowClass = value === 7 || value === 1 ? 'hover:shadow-lg' : 'hover:shadow-md';

                const customStyle = value <= 3 ? `style="background: linear-gradient(to bottom right, #EFF6FF, #DBEAFE); border-color: #5AA7C6;"` :
                                   value === 4 ? `style="background: linear-gradient(to bottom right, #f9fafb, #f3f4f6); border-color: #9ca3af;"` :
                                   `style="background: linear-gradient(to bottom right, #f0fdfa, #ccfdf7); border-color: #14b8a6;"`;

                const isChecked = responses[`q${questionNum}`] === value ? 'checked' : '';

                optionsHTML += `
                    <label for="q${questionNum}_${value}" class="cursor-pointer block mx-2">
                        <input type="radio" id="q${questionNum}_${value}" name="q${questionNum}" value="${value}" class="sr-only" ${isChecked} required>
                        <div class="modern-radio-option ${sizes[index]} rounded-xl border-2 ${shadowClass} transform hover:scale-105 transition-all duration-300 flex items-center justify-center group" data-value="${value}" ${customStyle}>
                            <div class="${innerSizes[index]} rounded-full opacity-0 group-hover:opacity-30 transition-all duration-300 flex items-center justify-center" style="background: ${value <= 3 ? '#5AA7C6' : value === 4 ? '#9ca3af' : '#14b8a6'};">
                                <div class="${dotSizes[index]} rounded-full bg-white opacity-0 transition-opacity duration-300"></div>
                            </div>
                        </div>
                    </label>
                `;
            });

            return optionsHTML;
        }

        function validateCurrentPage() {
            console.log('Validating page:', currentPage);

            const currentPageElement = document.getElementById(`page-${currentPage}`);
            if (!currentPageElement) {
                console.log('Page element not found:', `page-${currentPage}`);
                return false;
            }

            // Get all unique question names on this page
            const questionNames = new Set();
            const allInputs = currentPageElement.querySelectorAll('input[type="radio"]');
            console.log('Found radio inputs:', allInputs.length);
            allInputs.forEach(input => questionNames.add(input.name));
            console.log('Question names on page:', Array.from(questionNames));

            // Check if each question has been answered
            for (let questionName of questionNames) {
                const answered = currentPageElement.querySelector(`input[name="${questionName}"]:checked`);
                console.log(`Question ${questionName} answered:`, !!answered);
                if (!answered) {
                    // Use SweetAlert for better user experience
                    Swal.fire({
                        icon: 'warning',
                        title: 'Question Required',
                        text: `Please answer question ${questionName.replace('q', '')} before proceeding.`,
                        confirmButtonColor: '#5AA7C6'
                    });
                    return false;
                }
            }
            console.log('All questions answered on page', currentPage);
            return true;
        }

        function saveCurrentPageResponses() {
            const currentPageElement = document.getElementById(`page-${currentPage}`);
            const inputs = currentPageElement.querySelectorAll('input[type="radio"]:checked');

            inputs.forEach(input => {
                responses[input.name] = parseInt(input.value);
            });
        }

        function updateProgress() {
            const progressPercent = (currentPage / totalPages) * 100;
            document.getElementById('progress-bar').style.width = `${progressPercent}%`;
            document.getElementById('progress-text').textContent = `Page ${currentPage} of ${totalPages}`;
        }

        function updateNavigationButtons() {
            const prevBtn = document.getElementById('prev-btn');
            const nextBtn = document.getElementById('next-btn');
            const submitBtn = document.getElementById('submit-btn');

            prevBtn.disabled = currentPage === 1;

            if (currentPage === totalPages) {
                nextBtn.style.display = 'none';
                submitBtn.style.display = 'block';
                submitBtn.textContent = 'Complete Assessment';
                submitBtn.style.backgroundColor = '#5AA7C6';
            } else {
                nextBtn.style.display = 'block';
                submitBtn.style.display = 'none';
            }
        }

        function checkEarlyCompletion() {
            // Disabled: require all 60 questions before completion
            return false;
        }
    });

    // Assessment Mode Toggle Functionality
    document.addEventListener('DOMContentLoaded', function() {

    });
</script>

<!-- Include MBTI RL System Scripts (kept for future improvements) -->
<script src="{{ asset('js/mbti-tester.js') }}"></script>
<script src="{{ asset('js/mbti-rl-agent.js') }}"></script>
<script src="{{ asset('js/mbti-rl-enhanced.js') }}"></script>

<script>
// RL System Integration (background only - not used for assessment flow)
let rlSystem = null;

// Initialize RL system in background for future improvements
document.addEventListener('DOMContentLoaded', function() {
    initializeRLSystem();
});

async function initializeRLSystem() {
    try {
        console.log('🚀 Initializing MBTI RL System (background)...');
        rlSystem = new MBTIRLEnhanced();
        await rlSystem.trainAgent(50); // Quick training
        console.log('✅ RL system ready (background mode)');
    } catch (error) {
        console.error('❌ RL system initialization failed:', error);
    }
}

// Standard Assessment Flow (simplified)
function startStandardAssessment() {
    // Show standard UI elements
    const stepIndicators = document.querySelector('.step-indicator');
    if (stepIndicators) {
        stepIndicators.parentElement.style.display = 'flex';
    }

    const progressBar = document.getElementById('progress-bar');
    if (progressBar) {
        progressBar.parentElement.style.display = 'block';
    }

    // Initialize standard assessment
    currentPage = 1;
    showPage(currentPage);
    updateProgress();
    updateNavigationButtons();

    console.log('🎯 Standard assessment started');
}

// Set the main assessment function
window.startAssessment = startStandardAssessment;

</script>
@endpush
